CREATE TABLE "Users" (
"ID" SERIAL PRIMARY KEY,
"UserName" VARCHAR(100) NOT NULL,
"UserEmail" VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE "Orders" (
    "ID" SERIAL PRIMARY KEY,
    "UserID" INT REFERENCES "Users" ("ID"),
    "OrderDate" TIMESTAMP DEFAULT NOW()
);